version: '3.7'
services:
  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  pg_data:
